name: Deploy Bot to GCP

on:
  push:
    branches:
      - main
    paths:
      - 'bot/**'
      - '.github/workflows/deploy-bot.yml'

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Deploy to GCP VM
        uses: appleboy/ssh-action@v1.0.0
        env:
          DISCORD_BOT_TOKEN: ${{ secrets.DISCORD_BOT_TOKEN }}
          DISCORD_CLIENT_ID: ${{ secrets.DISCORD_CLIENT_ID }}
        with:
          host: 35.236.75.172
          username: ethan
          key: ${{ secrets.GCP_SSH_KEY }}
          envs: DISCORD_BOT_TOKEN,DISCORD_CLIENT_ID
          script: |
            cd ~/discord-bot
            
            # Clean directory to avoid conflicts
            rm -rf *
            rm -rf .git
            
            # Download latest code from bot directory
            curl -L https://github.com/EthanAIMS/discord-scheduler-bot/archive/refs/heads/main.tar.gz | tar xz --strip-components=2 discord-scheduler-bot-main/bot
            
            # Replace placeholders in config.json with actual secrets
            sed -i "s/DISCORD_BOT_TOKEN_PLACEHOLDER/$DISCORD_BOT_TOKEN/g" config.json
            sed -i "s/DISCORD_CLIENT_ID_PLACEHOLDER/$DISCORD_CLIENT_ID/g" config.json
            
            # Install dependencies if package.json changed
            npm install
            
            # Restart bot using PM2 (or pkill/start if not using PM2)
            if command -v pm2 &> /dev/null; then
              pm2 restart bot || pm2 start bot.js --name bot
            else
              pkill -f "node bot.js" || true
              nohup node bot.js > bot.log 2>&1 &
            fi
            
            echo "Bot deployed successfully!"
